# Generated by Django 2.2.7 on 2019-11-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='French',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('engname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Verber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ername', models.TextField()),
                ('erengname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Verbir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irname', models.TextField()),
                ('irengname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Verbre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rename', models.TextField()),
                ('reengname', models.TextField()),
            ],
        ),
    ]
